### ISSUE TITLE
Can't generate documentation for some crates (incl. standard library)

### ISSUE THREAD

**Issue by chubin** [Ruin0x11/oxidoc#15]
I tried to generate documentation for various crates installed locally, 
and everything worked like a charm for almost all of them except a couple of.
Documentation for the standard library was not generated too.

It seems to me, that  currently oxidoc can't generate documentation
for the current rust source code (or I do something wrong).

How to reproduce:
```
$ RUST_BACKTRACE=1 oxidoc -g ~/rust-source/rust/src/libstd/
Generating documentation for std-0.0.0
error: internal compiler error: Error constructed but not emitted

thread 'main' panicked at 'explicit panic', /home/igor/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.59.1/src/diagnostic_builder.rs:204:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
   6: <syntex_errors::diagnostic_builder::DiagnosticBuilder<'a> as core::ops::drop::Drop>::drop
   7: oxidoc::generation::generate_docs_for_path
   8: oxidoc::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  13: main
  14: __libc_start_main
  15: _start
```

Or with debug symboles:
```
...
   6: <syntex_errors::diagnostic_builder::DiagnosticBuilder<'a> as core::ops::drop::Drop>::drop
             at /home/igor/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.59.1/src/diagnostic_builder.rs:204
   7: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
   8: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
   9: oxidoc::generation::parse_crate
             at src/generation/mod.rs:158
  10: oxidoc::generation::cache_doc_for_crate
             at src/generation/mod.rs:125
  11: oxidoc::generation::generate_docs_for_path
             at src/generation/mod.rs:96
  12: oxidoc::generate
             at src/main.rs:86
...
```
Should I use old rust source code?
What version?

**Comment by schodet** [comment]
It seems that the `syntex_syntax` crate was not updated for a long time… I suppose this is the problem.

**Comment by chubin** [comment]
@schodet The question is, could it be easily fixed, or is it a big piece of work?

**Comment by schodet** [comment]
Not sure, it seems that `syntex_syntax` need to be copied/pasted from rust sources. If you can understand how it is “generated”, it may be simple, then hope that the API did not change.

Hum, the syntex repository has been replaced by a **Syntex is no longer maintained.** README file… May be `libsyntax` can now be used directly?

It seems to me that it would be simpler if oxidoc was using `librustdoc` to extract documentation, I think that it is the track I would follow if I ever work on this. `librustdoc` could generate a machine readable output next to HTML output, and a command line help system would use it.

**Comment by schodet** [comment]
To actually reply to your question… yes I suppose this is a big piece of work.

**Comment by Ruin0x11** [comment]
Hi. I don't actually maintain this anymore, it uses really old versions of
syntex/rustc. I recall it was a lot of work to keep up with the compiler
internals at the time.

2019年5月15日(水) 13:34 Nicolas Schodet <notifications@github.com>:

**Comment by schodet** [comment]
Then I suppose that https://github.com/rust-lang/rfcs/issues/650 should be reopen. Are you OK with this?

**Comment by Ruin0x11** [comment]
Sure, go ahead.

2019年5月15日(水) 14:26 Nicolas Schodet <notifications@github.com>:
